<?php
/**
 * @file
 * pages_issues.pages_default.inc
 */

/**
 * Implements hook_default_page_manager_pages().
 */
function pages_issues_default_page_manager_pages() {
  $page = new stdClass();
  $page->disabled = FALSE; /* Edit this to true to make a default page disabled initially */
  $page->api_version = 1;
  $page->name = 'issues';
  $page->task = 'page';
  $page->admin_title = 'Issues';
  $page->admin_description = 'Designed to show issue related content.';
  $page->path = 'issue';
  $page->access = array(
    'logic' => 'and',
  );
  $page->menu = array();
  $page->arguments = array();
  $page->conf = array(
    'admin_paths' => FALSE,
  );
  $page->default_handlers = array();
  $handler = new stdClass();
  $handler->disabled = FALSE; /* Edit this to true to make a default handler disabled initially */
  $handler->api_version = 1;
  $handler->name = 'page_issues_panel_context';
  $handler->task = 'page';
  $handler->subtask = 'issues';
  $handler->handler = 'panel_context';
  $handler->weight = 0;
  $handler->conf = array(
    'title' => 'Issue',
    'no_blocks' => 1,
    'pipeline' => 'standard',
    'body_classes_to_remove' => '',
    'body_classes_to_add' => '',
    'css_id' => '',
    'css' => '',
    'contexts' => array(),
    'relationships' => array(),
    'access' => array(
      'logic' => 'and',
    ),
  );
  $display = new panels_display();
  $display->layout = 'bootstrap_twocol_stacked';
  $display->layout_settings = array();
  $display->panel_settings = array(
    'style_settings' => array(
      'default' => NULL,
      'top' => NULL,
      'left' => NULL,
      'right' => NULL,
      'bottom' => NULL,
    ),
  );
  $display->cache = array();
  $display->title = '';
  $display->uuid = '73738d01-e70d-484e-849a-e9c5d3f17d5d';
  $display->content = array();
  $display->panels = array();
    $pane = new stdClass();
    $pane->pid = 'new-8dd223d7-22c6-459b-ba48-e29e1638e1d6';
    $pane->panel = 'left';
    $pane->type = 'views_panes';
    $pane->subtype = 'issue-panel_pane_1';
    $pane->shown = TRUE;
    $pane->access = array();
    $pane->configuration = array(
      'items_per_page' => '10',
      'offset' => '0',
      'override_title' => 0,
      'override_title_text' => '',
    );
    $pane->cache = array();
    $pane->style = array(
      'settings' => NULL,
    );
    $pane->css = array();
    $pane->extras = array();
    $pane->position = 0;
    $pane->locks = array();
    $pane->uuid = '8dd223d7-22c6-459b-ba48-e29e1638e1d6';
    $display->content['new-8dd223d7-22c6-459b-ba48-e29e1638e1d6'] = $pane;
    $display->panels['left'][0] = 'new-8dd223d7-22c6-459b-ba48-e29e1638e1d6';
    $pane = new stdClass();
    $pane->pid = 'new-1a04125f-3b65-4b4e-ab13-1b043a5cae78';
    $pane->panel = 'top';
    $pane->type = 'node';
    $pane->subtype = 'node';
    $pane->shown = TRUE;
    $pane->access = array();
    $pane->configuration = array(
      'nid' => '3',
      'links' => 1,
      'leave_node_title' => 0,
      'identifier' => '',
      'build_mode' => 'teaser',
      'link_node_title' => 0,
      'override_title' => 0,
      'override_title_text' => '',
    );
    $pane->cache = array();
    $pane->style = array(
      'settings' => NULL,
    );
    $pane->css = array();
    $pane->extras = array();
    $pane->position = 0;
    $pane->locks = array();
    $pane->uuid = '1a04125f-3b65-4b4e-ab13-1b043a5cae78';
    $display->content['new-1a04125f-3b65-4b4e-ab13-1b043a5cae78'] = $pane;
    $display->panels['top'][0] = 'new-1a04125f-3b65-4b4e-ab13-1b043a5cae78';
  $display->hide_title = PANELS_TITLE_FIXED;
  $display->title_pane = 'new-8dd223d7-22c6-459b-ba48-e29e1638e1d6';
  $handler->conf['display'] = $display;
  $page->default_handlers[$handler->name] = $handler;
  $pages['issues'] = $page;

  return $pages;

}
